name: Deploy React
on: 
  push:
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Install Dependencies
        run: bun i
      - name: Run ESLint
        run: bun run lint
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Install Dependencies
        run: bun i
      - name: Build Project
        run: bun run build
      - name: List files
        run: ls -l dist
      - name: Deploy
        run: echo "Deploying..."